// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShounenGaming.DataAccess.Persistence;

#nullable disable

namespace ShounenGaming.DataAccess.Persistence.Migrations
{
    [DbContext(typeof(ShounenGamingContext))]
    [Migration("20230525115403_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MangaChapterMangaUserData", b =>
                {
                    b.Property<int>("ChaptersReadId")
                        .HasColumnType("integer");

                    b.Property<int>("MangaUserDataId")
                        .HasColumnType("integer");

                    b.HasKey("ChaptersReadId", "MangaUserDataId");

                    b.HasIndex("MangaUserDataId");

                    b.ToTable("MangaChapterMangaUserData");
                });

            modelBuilder.Entity("MangaMangaTag", b =>
                {
                    b.Property<int>("MangasId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("MangasId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("MangaMangaTag");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Base.Bot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Base.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiscordImage")
                        .HasColumnType("text");

                    b.Property<bool>("DiscordVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReleasing")
                        .HasColumnType("boolean");

                    b.Property<long?>("MangaAniListID")
                        .HasColumnType("bigint");

                    b.Property<long?>("MangaMyAnimeListID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WriterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MangaAniListID")
                        .IsUnique();

                    b.HasIndex("MangaMyAnimeListID")
                        .IsUnique();

                    b.HasIndex("WriterId");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaAlternativeName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MangaId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MangaId");

                    b.ToTable("MangaAlternativeNames");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MangaId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MangaId");

                    b.ToTable("MangaChapters");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BrokenLink")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MangaId")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MangaId");

                    b.ToTable("MangaSources");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MangaTags");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<int?>("MangaChapterId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReleasedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MangaChapterId");

                    b.ToTable("MangaTranslations");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaUserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MangaId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MangaId");

                    b.HasIndex("UserId");

                    b.ToTable("MangaUsersData");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaWriter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MangaWriters");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangasUserAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MangaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MangaId");

                    b.ToTable("MangaUsersActions");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.Tier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("TierlistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TierlistId");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.TierChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserTierlistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TierId");

                    b.HasIndex("UserTierlistId");

                    b.ToTable("TierChoices");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.Tierlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Tierlists");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.TierlistCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TierlistCategories");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.TierlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TierChoiceId")
                        .HasColumnType("integer");

                    b.Property<int?>("TierlistId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TierChoiceId");

                    b.HasIndex("TierlistId");

                    b.ToTable("TierlistItems");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.UserTierlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TierlistId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TierlistId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTierlists");
                });

            modelBuilder.Entity("MangaChapterMangaUserData", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Mangas.MangaChapter", null)
                        .WithMany()
                        .HasForeignKey("ChaptersReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShounenGaming.Core.Entities.Mangas.MangaUserData", null)
                        .WithMany()
                        .HasForeignKey("MangaUserDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MangaMangaTag", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Mangas.Manga", null)
                        .WithMany()
                        .HasForeignKey("MangasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShounenGaming.Core.Entities.Mangas.MangaTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.Manga", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Mangas.MangaWriter", "Writer")
                        .WithMany("Mangas")
                        .HasForeignKey("WriterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaAlternativeName", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Mangas.Manga", null)
                        .WithMany("AlternativeNames")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaChapter", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Mangas.Manga", null)
                        .WithMany("Chapters")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaSource", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Mangas.Manga", null)
                        .WithMany("Sources")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaTranslation", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Mangas.MangaChapter", null)
                        .WithMany("Translations")
                        .HasForeignKey("MangaChapterId");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaUserData", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Mangas.Manga", "Manga")
                        .WithMany("UsersData")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShounenGaming.Core.Entities.Base.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangasUserAction", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Mangas.Manga", "Manga")
                        .WithMany()
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.Tier", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Tierlists.Tierlist", null)
                        .WithMany("DefaultTiers")
                        .HasForeignKey("TierlistId");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.TierChoice", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Tierlists.Tier", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShounenGaming.Core.Entities.Tierlists.UserTierlist", null)
                        .WithMany("Choices")
                        .HasForeignKey("UserTierlistId");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.Tierlist", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Tierlists.TierlistCategory", "Category")
                        .WithMany("Tierlists")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShounenGaming.Core.Entities.Base.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.TierlistItem", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Tierlists.TierChoice", null)
                        .WithMany("Items")
                        .HasForeignKey("TierChoiceId");

                    b.HasOne("ShounenGaming.Core.Entities.Tierlists.Tierlist", null)
                        .WithMany("Items")
                        .HasForeignKey("TierlistId");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.UserTierlist", b =>
                {
                    b.HasOne("ShounenGaming.Core.Entities.Tierlists.Tierlist", "Tierlist")
                        .WithMany()
                        .HasForeignKey("TierlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShounenGaming.Core.Entities.Base.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tierlist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.Manga", b =>
                {
                    b.Navigation("AlternativeNames");

                    b.Navigation("Chapters");

                    b.Navigation("Sources");

                    b.Navigation("UsersData");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaChapter", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Mangas.MangaWriter", b =>
                {
                    b.Navigation("Mangas");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.TierChoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.Tierlist", b =>
                {
                    b.Navigation("DefaultTiers");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.TierlistCategory", b =>
                {
                    b.Navigation("Tierlists");
                });

            modelBuilder.Entity("ShounenGaming.Core.Entities.Tierlists.UserTierlist", b =>
                {
                    b.Navigation("Choices");
                });
#pragma warning restore 612, 618
        }
    }
}
