name: Deploy to Dev

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    #types:
     # - closed
     
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release

  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/tigasramos/shounen-gaming-server:dev

  deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Redeploy Stack
        uses: wirgen/portainer-stack-redeploy-action@v1.1
        with:
          portainerUrl: https://portainer.shounengaming.xyz
          accessToken: ${{ secrets.PORTAINER_TOKEN }}
          stackId: 243
          endpointId: 2
