name: Deploy to Dev

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker-registry.shounengaming.xyz
  DOCKER_IMAGE_NAME: shounen-gaming-server
  DOCKER_TAG: dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release

  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
          
      - name: Publish Docker image
        run: docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_TAG .
        
      - name: Push Docker image
        run: docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_TAG

  deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Redeploy Stack
        uses: wirgen/portainer-stack-redeploy-action@v1.1
        with:
          portainerUrl: https://portainer.shounengaming.xyz
          accessToken: ${{ secrets.PORTAINER_TOKEN }}
          stackId: 236
          endpointId: 2
