name: Deploy to Dev

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release

  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Publish Docker image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: https://docker-registry.shounengaming.xyz/shounen-gaming-server:dev

  deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Redeploy Stack
        uses: wirgen/portainer-stack-redeploy-action@v1.1
        with:
          portainerUrl: https://portainer.shounengaming.xyz
          accessToken: ${{ secrets.PORTAINER_TOKEN }}
          stackId: 236
          endpointId: 3
